### ISSUE TITLE
配置文件无法找到，以及server.add_help_message属性不存在

### ISSUE THREAD

**Issue by chenjie1234567890** [Forgot-Dream/MCDR-AutoCleaner#1]
![image](https://user-images.githubusercontent.com/39559452/79963832-76331a00-84bc-11ea-8a0f-64d402d30007.png)
![image](https://user-images.githubusercontent.com/39559452/79963866-821edc00-84bc-11ea-8aee-8d6f9e3282f4.png)

**Comment by Forgot-Dream** [comment]
请使用最新版本mcdr 并且确定给mcdr全部的可执行权限 而且插件确保是最新的commit
